---
- name: Get the aws instance_id into a variable
  action: uri url="http://169.254.169.254/latest/meta-data/instance-id" return_content=yes
  register: instance_id

- name: get the public_ip address into a variable
  shell: wget -qO- http://ipecho.net/plain ; echo
  register: public_ip